export const VOTE = 'VOTE'

export const FETCH_SELECTED_GAME = 'FETCH_SELECTED_GAME'
export const SELECT_GAME = 'SELECT_GAME'
export const START_NEW_VOTE = 'START_NEW_VOTE'

export const GET_CHAMPIONS = 'GET_CHAMPIONS'