export const VOTE = 'VOTE'
export const SIMULATE_VOTE = 'SIMULATE_VOTE'

export const START_NEW_VOTE = 'START_NEW_VOTE'

export const GET_CANDIDATES = 'GET_CANDIDATES'

export const GET_TOP_TWITCH_GAMES = 'GET_TOP_TWITCH_GAMES'
