export const VOTE = 'VOTE'

export const START_NEW_VOTE = 'START_NEW_VOTE'

export const GET_CANDIDATES = 'GET_CANDIDATES'

export const GET_TOP_TWITCH_GAMES = 'GET_TOP_TWITCH_GAMES'

export const SAVE_GAME_WHITELIST = 'SAVE_GAME_WHITELIST'

export const SET_HEARTHSTONE_DECKS = 'SET_HEARTHSTONE_DECKS'

export const TOGGLE_SHOW_NAME_IN_GRID = 'TOGGLE_SHOW_NAME_IN_GRID'