
export const SET_GAME = 'SET_GAME'
export const SET_VOTE_CATEGORY = 'SET_VOTE_CATEGORY'
export const SET_VOTE_MODE = 'SET_VOTE_MODE'

export const SET_AUTH = 'SET_AUTH'
export const SET_CURRENT_VOTE = 'SET_CURRENT_VOTE'
export const SET_USER_VOTE = 'SET_USER_VOTE'
export const ADD_VOTE = 'ADD_VOTE'
export const START_NEW_VOTE = 'START_NEW_VOTE'
export const SET_CANDIDATES = 'SET_CANDIDATES'
export const SET_FILTERS = 'SET_FILTERS'
export const RESET_FILTERS = 'RESET_FILTERS'

export const SELECT_CANDIDATE = 'SELECT_CANDIDATE'

export const SET_WHITELIST = 'SET_WHITELIST'

export const SET_HEARTHSTONE_DECKS = 'SET_HEARTHSTONE_DECKS'

export const SET_TOP_TWITCH_GAMES = 'SET_TOP_TWITCH_GAMES'
export const SET_SEARCHED_GAMES = 'SET_SEARCHED_GAMES'
// testing
export const TOGGLE_VOTE_SIMULATION = 'TOGGLE_VOTE_SIMULATION'
